---
title: "PanMyeloid Assignment--Data Exploration"
author: "ZHANG, Yiling"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    code_folding: show
    self_contained: true
    thumbnails: false
    lightbox: true
    df_print: paged
    gallery: false
    highlight: tango
pkgdown:
  as_is: true    
---


```{r include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  fig.align = "center",
  fig.width = 6,
  autodep = TRUE,
  cache.lazy = FALSE
)
```

# 1. Environment Setting

```{r}
library(Seurat)
library(dplry)
library(ggplot2)
library(cowplot)
```

```{r}
packageVersion("Seurat")
```

# 2. Collected Dataset(MEL) Preprocessing
## 2.1 Create Seurat Object
```{r}

```




# Supplemental Information

<details><summary>**▶ Session Info**</summary>
```{r echo=FALSE}
sessionInfo()
```
</details>


<details><summary>**▶ Server Info**</summary>
* Linux Version
```{bash echo=FALSE}
cat /etc/os-release
```

* CPU info
```{bash echo=FALSE}
lscpu | head -25
```
</details>